# Generated by Django 5.1.7 on 2025-03-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('activity', models.CharField(choices=[('Sedentary', 'Little or no exercise'), ('Light activity', 'Light exercise/sports 1-3 days/week'), ('Moderate', 'Moderate exercise/sports 3-5 days/week'), ('Active', 'Hard exercise/sports 6-7 days a week'), ('Very active', 'Very hard exercise or physical job')], max_length=20)),
                ('goal_weight', models.FloatField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='accounts.profile')),
            ],
        ),
    ]
