# Generated by Django 5.1.7 on 2025-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Maintain', 'Maintain Weight'), ('Mild Loss', 'Mild Weight Loss (-250 kcal)'), ('Loss', 'Weight Loss (-500 kcal)'), ('Extreme Loss', 'Extreme Weight Loss (-1000 kcal)'), ('Mild Gain', 'Mild Weight Gain (+250 kcal)'), ('Gain', 'Weight Gain (+500 kcal)'), ('Extreme Gain', 'Extreme Weight Gain (+1000 kcal)')], default='Maintain', max_length=20),
        ),
    ]
