# Generated by Django 5.1.7 on 2025-03-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0002_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='daily_calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
