# Generated by Django 5.1.7 on 2025-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0004_alter_goal_daily_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='daily_carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='daily_fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='daily_protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
