# Generated by Django 5.1.7 on 2025-03-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
        ('goal_app', '0005_goal_daily_carbohydrates_goal_daily_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Extreme Gain', 'Extreme Weight Gain (+1000 kcal)'), ('Gain', 'Weight Gain (+500 kcal)'), ('Mild Gain', 'Mild Weight Gain (+250 kcal)'), ('Maintain', 'Maintain Weight'), ('Mild Loss', 'Mild Weight Loss (-250 kcal)'), ('Loss', 'Weight Loss (-500 kcal)'), ('Extreme Loss', 'Extreme Weight Loss (-1000 kcal)')], default='Maintain', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='accounts.profile'),
        ),
    ]
