# Generated by Django 5.1.1 on 2025-04-06 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0007_goal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
