# Generated by Django 5.1.1 on 2025-04-02 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('My Meals', 'My Meals'), ('Pork', 'Pork'), ('Beef', 'Beef'), ('Poultry', 'Poultry'), ('Seafood', 'Seafood'), ('Fast Food', 'Fast Food'), ('Dairy', 'Dairy'), ('Cereal, Grains & Pasta', 'Cereal, Grains & Pasta'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Sweets & Snacks', 'Sweets & Snacks'), ('Drinks', 'Drinks'), ('Other', 'Other')], default='My Meals', max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='grams_portion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
