# Generated by Django 5.1.1 on 2025-04-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
        ('meals_app', '0002_alter_dailymeal_meal_type_alter_meal_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_calories', models.FloatField(default=0.0)),
                ('total_protein', models.FloatField(default=0.0)),
                ('total_carbs', models.FloatField(default=0.0)),
                ('total_sugars', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_fats', models.FloatField(default=0.0)),
                ('total_fiber', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_sodium', models.FloatField(blank=True, default=0.0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumptions', to='accounts.profile')),
            ],
        ),
    ]
