# Generated by Django 5.1.1 on 2025-04-18 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exercise_type', models.CharField(choices=[('cardio', 'Cardio'), ('machine', 'Machine'), ('cable', 'Cable'), ('dumbbell', 'Dumbbell'), ('free_weight', 'Free Weight'), ('body_weight', 'Body Weight'), ('other', 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('effort_level', models.PositiveIntegerField(blank=True, help_text='RPE (Rate of Perceived Exertion) from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_exercise', to='trainings_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps_number', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('training_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='trainings_app.trainingexercise')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('chest', 'Chest'), ('back', 'Back'), ('shoulder', 'Shoulder'), ('arms', 'Arms'), ('legs', 'Legs'), ('full_body', 'Full Body'), ('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('body_weight', 'Body Weight'), ('other', 'Other')], max_length=30)),
                ('gym', models.CharField(blank=True, max_length=100, null=True)),
                ('training_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_exercise', to='trainings_app.trainingsession'),
        ),
    ]
