# Generated by Django 5.1.1 on 2025-04-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_picture',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_picture/'),
        ),
    ]
